FROM node:20-alpine

WORKDIR /app

# 替换为淘宝镜像源加速
RUN npm config set registry https://registry.npmmirror.com/

# 先复制 package.json
COPY package*.json ./
RUN npm install

# 复制源码
COPY . .

# 跑 build（检查语法、import 错误、是否能编译过）
CMD ["npm", "run", "build"]
